import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // 旧デザイン（未リニューアルのページ用に残す。全画面移行後に削除）
        brand: {
          50: "#f3f6fb",
          100: "#e4ebf6",
          200: "#c6d5ec",
          300: "#9bb6dd",
          400: "#6a90ca",
          500: "#476fb5",
          600: "#365799",
          700: "#2d477c",
          800: "#293e67",
          900: "#263657",
        },
        // Stitch で生成した新デザインのトークン（Material 3 風の命名）
        "surface-dim": "#e2d9c6",
        "error-container": "#ffdad6",
        tertiary: "#302f25",
        outline: "#737872",
        "primary-fixed-dim": "#b7ccb8",
        "on-secondary-container": "#763404",
        "surface-container": "#f7edd9",
        "tertiary-fixed": "#e7e2d4",
        primary: "#213225",
        "surface-tint": "#506353",
        "outline-variant": "#c3c8c1",
        "on-tertiary-fixed": "#1d1c13",
        background: "#fff8f0",
        "primary-fixed": "#d3e8d3",
        "surface-variant": "#ebe2ce",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#49473c",
        secondary: "#944a1b",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#faf0dc",
        "on-background": "#1f1b0f",
        "on-error-container": "#93000a",
        "surface-container-low": "#fdf3df",
        "on-tertiary-container": "#b6b2a5",
        "surface-container-high": "#f1e7d4",
        "secondary-fixed-dim": "#ffb68e",
        "on-surface-variant": "#434843",
        "secondary-fixed": "#ffdbca",
        surface: "#fff8f0",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#cbc6b8",
        "on-primary-fixed": "#0e1f13",
        "inverse-primary": "#b7ccb8",
        "tertiary-container": "#47453a",
        "on-primary": "#ffffff",
        "on-primary-container": "#a3b8a4",
        "on-primary-fixed-variant": "#394b3c",
        "on-surface": "#1f1b0f",
        "surface-container-highest": "#ebe2ce",
        "on-secondary-fixed-variant": "#763304",
        "inverse-surface": "#353023",
        "on-secondary-fixed": "#331200",
        "secondary-container": "#fe9f69",
        "surface-bright": "#fff8f0",
        "primary-container": "#37493a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "gutter-grid": "16px",
        "section-gap": "48px",
        "margin-main": "20px",
      },
      fontFamily: {
        "label-sm": ["var(--font-jakarta)", "sans-serif"],
        "display-lg": ["var(--font-noto-serif)", "serif"],
        "display-md": ["var(--font-noto-serif)", "serif"],
        "headline-sm": ["var(--font-noto-serif)", "serif"],
        "body-lg": ["var(--font-jakarta)", "sans-serif"],
        "body-md": ["var(--font-jakarta)", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-lg": ["32px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "700" }],
        "display-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.5", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.7", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
